GET http://localhost:3001/api/foods/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF2aWxsZWdhcyIsImlkIjoiNjA4ODI4NzEyYzE5ODMxMjljNmQ3OWNlIiwiaWF0IjoxNjIwMDMwMzY5fQ.oUjS5yKU9J6a9egNapIqzOtsn9vNJ-MziXdqVNRTx6E